[window]
padding.x = 10
padding.y = 10
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.8
blur = true 
dimensions = { columns = 145, lines = 55}

[font]
normal.family = "JetBrains Mono"
bold.family = "JetBrains Mono"
italic.family = "JetBrains Mono"
bold_italic.family = "JetBrains Mono"
size = 11.0
