#!/bin/sh

fileName="$HOME/code/bgudna.github.io/_posts/$(date +%Y-%m-%d)-noodles.md"

if [ ! -f $fileName ]; then

    echo "---" >> $fileName
    echo "layout: post" >> $fileName
    echo "title: Random ramblings at $(date +%d-%m-%Y)" >> $fileName
    echo "permalink: /$RANDOM/" >> $fileName
    echo "---" >> $fileName
    echo "# Notes for this day" >> $fileName
fi

vim -c "norm Go" \
 -c "norm Go## $(date +%H:%M)" \
 -c "norm G2o" \
 -c "norm zz" \
 -c "startinsert" $fileName
