#!/bin/sh

fileName="$HOME/docs/note-$(date +%d-%m-%Y).md"

if [ ! -f $fileName ]; then 
    echo "# Notes for $(date +%d-%m-%Y)" > $fileName
fi

vim -c "norm Go" \
 -c "norm Go## $(date +%H:%M)" \
 -c "norm G2o" \
 -c "norm zz" \
 -c "startinsert" $fileName
